from typing import Protocol, List, Dict, Any, AsyncGenerator, Optional

class IDatabase(Protocol):
    def create_session(self, session_id: str) -> None: ...
    def update_session(self, session_id: str, data: Dict[str, Any]) -> None: ...
    def get_session(self, session_id: str) -> Optional[Dict[str, Any]]: ...

class IBlobStorage(Protocol):
    def generate_upload_urls(self, session_id: str, files: List[str]) -> List[dict]: ...

class ITaskQueue(Protocol):
    def enqueue_room_processing(self, session_id: str, room: str) -> None: ...
    def enqueue_perspective_correction(self, session_id: str, room: str) -> None: ...

class IEventPublisher(Protocol):
    async def publish_progress(self, session_id: str, room: str, status: str) -> None: ...

class IProgressSubscriber(Protocol):
    async def subscribe(self, channel: str) -> AsyncGenerator[Optional[Dict[str, Any]], None]: ...
