from typing import List, AsyncGenerator, Protocol, Optional, Dict, Any

class IDatabase(Protocol):
    def save_session(self, session_id: str, data: dict): ...
    def get_session(self, session_id: str) -> dict: ...
    def save_processing_result(self, session_id: str, result: dict): ...
    def get_processing_results(self, session_id: str) -> List[dict]: ...
    
    # Job-related methods for async polling
    def save_job(self, job_id: str, session_id: str, status: str, idempotency_key: str, result: Optional[dict] = None, error: Optional[str] = None): ...
    def get_job(self, job_id: str) -> Optional[dict]: ...
    def get_job_by_idempotency_key(self, idempotency_key: str) -> Optional[dict]: ...
    def get_active_jobs(self, session_id: str) -> List[dict]: ...
    def get_jobs(self, job_ids: List[str]) -> List[dict]: ...

    def get_agency_quota(self, agency_id: str) -> dict: ...
    def increment_quota_usage(self, agency_id: str, amount: int) -> bool: ...
    def save_style_image(self, agency_id: str, blob_path: str) -> List[str]: ...
    def get_style_images(self, agency_id: str) -> List[str]: ...
    def save_training_pair(self, agency_id: str, bracket_paths: List[str], final_path: str) -> None: ...

class IBlobStorage(Protocol):
    def generate_upload_urls(self, session_id: str, files: List[str]) -> List[dict]: ...
    def download_blobs(self, session_id: str, files: List[str]) -> List[bytes]: ...

    def upload_blob(self, session_id: str, filename: str, data: bytes, content_type: str) -> str: ...
    def upload_blob_direct(self, blob_path: str, data: bytes, content_type: str) -> str: ...
    def generate_signed_url(self, blob_path: str, expiration_minutes: int = 15) -> str: ...
    def delete_blob(self, blob_path: str) -> None: ...

class ITaskQueue(Protocol):
    def enqueue_room_processing(self, session_id: str, room_name: str, photos: List[str]): ...
    def enqueue_job(self, job_id: str, session_id: str, room_name: str, photos: List[str]): ...

class IEventPublisher(Protocol):
    async def publish_progress(self, session_id: str, room: str, status: str, progress: Optional[int] = None): ...

class IProgressSubscriber(Protocol):
    async def subscribe(self, session_id: str) -> AsyncGenerator[str, None]: ...
