from typing import List, AsyncGenerator, Protocol, Optional

class IDatabase(Protocol):
    def save_session(self, session_id: str, data: dict): ...
    def get_session(self, session_id: str) -> dict: ...
    def save_processing_result(self, session_id: str, result: dict): ...
    def get_processing_results(self, session_id: str) -> List[dict]: ...

class IBlobStorage(Protocol):
    def generate_upload_urls(self, session_id: str, files: List[str]) -> List[dict]: ...
    def download_blobs(self, session_id: str, files: List[str]) -> List[bytes]: ...
    def upload_blob(self, session_id: str, filename: str, data: bytes, content_type: str) -> str: ...

class ITaskQueue(Protocol):
    def enqueue_room_processing(self, session_id: str, room_name: str, photos: List[str]): ...

class IEventPublisher(Protocol):
    async def publish_progress(self, session_id: str, room: str, status: str, progress: Optional[int] = None): ...

class IProgressSubscriber(Protocol):
    async def subscribe(self, session_id: str) -> AsyncGenerator[str, None]: ...
